# config/packages/security.yaml
security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
    providers:
            users:
                entity:
                    class: App\Entity\User
                    property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            json_login:
                check_path: app_login
                username_path: email
                password_path: password
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
            logout:
                path: app_logout
                target: /