# config/packages/security.yaml
security:
    providers:
            app_user_provider:
                entity:
                    class: App\Entity\User
                    property: email
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            anonymous: ~
            json_login:
                check_path: app_login
                username_path: email, apiToken
                password_path: password
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
            logout:
                path: app_logout