controllers:
    resource: ../../src/Controller
    type: annotation

api:
    resource: ../../src/Controller/LibraryController.php
    type: annotation
    prefix: /api/

dessertsUser:
    resource: ../../src/Controller/DessertsUserController.php
    type: annotation
    prefix: /list

kernel:
    resource: ../../src/Kernel.php
    type: annotation
