<?php

namespace ContainerTGHPWgH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vi0VQFSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vi0VQFS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vi0VQFS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\LibraryController::list' => ['privates', '.service_locator.jV8FHAs', 'get_ServiceLocator_JV8FHAsService', true],
            'App\\Controller\\UsersController::registration' => ['privates', '.service_locator.JvKr5ux', 'get_ServiceLocator_JvKr5uxService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.Bv1nHN9', 'get_ServiceLocator_Bv1nHN9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'kernel::terminate' => ['privates', '.service_locator.Bv1nHN9', 'get_ServiceLocator_Bv1nHN9Service', true],
            'App\\Controller\\LibraryController:list' => ['privates', '.service_locator.jV8FHAs', 'get_ServiceLocator_JV8FHAsService', true],
            'App\\Controller\\UsersController:registration' => ['privates', '.service_locator.JvKr5ux', 'get_ServiceLocator_JvKr5uxService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'kernel:terminate' => ['privates', '.service_locator.Bv1nHN9', 'get_ServiceLocator_Bv1nHN9Service', true],
        ], [
            'App\\Controller\\LibraryController::list' => '?',
            'App\\Controller\\UsersController::registration' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\LibraryController:list' => '?',
            'App\\Controller\\UsersController:registration' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
