<?php

namespace ContainerNqwUFEM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JV8FHAsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jV8FHAs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jV8FHAs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dessertRepository' => ['privates', 'App\\Repository\\DessertRepository', 'getDessertRepositoryService', true],
        ], [
            'dessertRepository' => 'App\\Repository\\DessertRepository',
        ]);
    }
}
