<?php

namespace ContainerMEJnBUG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M4A7sSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M4_A7sS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M4_A7sS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dessertUserRepository' => ['privates', 'App\\Repository\\DessertUserRepository', 'getDessertUserRepositoryService', true],
        ], [
            'dessertUserRepository' => 'App\\Repository\\DessertUserRepository',
        ]);
    }
}
