<?php

namespace ContainerMEJnBUG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLibraryControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\LibraryController' shared autowired service.
     *
     * @return \App\Controller\LibraryController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'LibraryController.php';

        $container->services['App\\Controller\\LibraryController'] = $instance = new \App\Controller\LibraryController(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));

        $instance->setContainer(($container->privates['.service_locator.0QcI221'] ?? $container->load('get_ServiceLocator_0QcI221Service'))->withContext('App\\Controller\\LibraryController', $container));

        return $instance;
    }
}
