<?php

namespace ContainerFxsV89x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HXwdH0TService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hXwdH0T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hXwdH0T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\DessertListUserController::create' => ['privates', '.service_locator.rnVfbDt', 'get_ServiceLocator_RnVfbDtService', true],
            'App\\Controller\\DessertListUserController::delete' => ['privates', '.service_locator.M4_A7sS', 'get_ServiceLocator_M4A7sSService', true],
            'App\\Controller\\DessertListUserController::getDessertList' => ['privates', '.service_locator.n9lCwcd', 'get_ServiceLocator_N9lCwcdService', true],
            'App\\Controller\\DessertsUserController::create' => ['privates', '.service_locator.gHATnNU', 'get_ServiceLocator_GHATnNUService', true],
            'App\\Controller\\DessertsUserController::list' => ['privates', '.service_locator.M4_A7sS', 'get_ServiceLocator_M4A7sSService', true],
            'App\\Controller\\LibraryController::create' => ['privates', '.service_locator.rnVfbDt', 'get_ServiceLocator_RnVfbDtService', true],
            'App\\Controller\\LibraryController::list' => ['privates', '.service_locator.jV8FHAs', 'get_ServiceLocator_JV8FHAsService', true],
            'App\\Controller\\UsersController::registration' => ['privates', '.service_locator.JO2SHr.', 'get_ServiceLocator_JO2SHr_Service', true],
            'App\\Controller\\UsersController::totalList' => ['privates', '.service_locator.9BcEIRl', 'get_ServiceLocator_9BcEIRlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.Bv1nHN9', 'get_ServiceLocator_Bv1nHN9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'kernel::terminate' => ['privates', '.service_locator.Bv1nHN9', 'get_ServiceLocator_Bv1nHN9Service', true],
            'App\\Controller\\DessertListUserController:create' => ['privates', '.service_locator.rnVfbDt', 'get_ServiceLocator_RnVfbDtService', true],
            'App\\Controller\\DessertListUserController:delete' => ['privates', '.service_locator.M4_A7sS', 'get_ServiceLocator_M4A7sSService', true],
            'App\\Controller\\DessertListUserController:getDessertList' => ['privates', '.service_locator.n9lCwcd', 'get_ServiceLocator_N9lCwcdService', true],
            'App\\Controller\\DessertsUserController:create' => ['privates', '.service_locator.gHATnNU', 'get_ServiceLocator_GHATnNUService', true],
            'App\\Controller\\DessertsUserController:list' => ['privates', '.service_locator.M4_A7sS', 'get_ServiceLocator_M4A7sSService', true],
            'App\\Controller\\LibraryController:create' => ['privates', '.service_locator.rnVfbDt', 'get_ServiceLocator_RnVfbDtService', true],
            'App\\Controller\\LibraryController:list' => ['privates', '.service_locator.jV8FHAs', 'get_ServiceLocator_JV8FHAsService', true],
            'App\\Controller\\UsersController:registration' => ['privates', '.service_locator.JO2SHr.', 'get_ServiceLocator_JO2SHr_Service', true],
            'App\\Controller\\UsersController:totalList' => ['privates', '.service_locator.9BcEIRl', 'get_ServiceLocator_9BcEIRlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'kernel:terminate' => ['privates', '.service_locator.Bv1nHN9', 'get_ServiceLocator_Bv1nHN9Service', true],
        ], [
            'App\\Controller\\DessertListUserController::create' => '?',
            'App\\Controller\\DessertListUserController::delete' => '?',
            'App\\Controller\\DessertListUserController::getDessertList' => '?',
            'App\\Controller\\DessertsUserController::create' => '?',
            'App\\Controller\\DessertsUserController::list' => '?',
            'App\\Controller\\LibraryController::create' => '?',
            'App\\Controller\\LibraryController::list' => '?',
            'App\\Controller\\UsersController::registration' => '?',
            'App\\Controller\\UsersController::totalList' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\DessertListUserController:create' => '?',
            'App\\Controller\\DessertListUserController:delete' => '?',
            'App\\Controller\\DessertListUserController:getDessertList' => '?',
            'App\\Controller\\DessertsUserController:create' => '?',
            'App\\Controller\\DessertsUserController:list' => '?',
            'App\\Controller\\LibraryController:create' => '?',
            'App\\Controller\\LibraryController:list' => '?',
            'App\\Controller\\UsersController:registration' => '?',
            'App\\Controller\\UsersController:totalList' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
