<?php

namespace ContainerFxsV89x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GHATnNUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gHATnNU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gHATnNU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dessertListUserRepository' => ['privates', 'App\\Repository\\DessertListUserRepository', 'getDessertListUserRepositoryService', true],
            'validator' => ['services', 'validator', 'getValidatorService', false],
        ], [
            'dessertListUserRepository' => 'App\\Repository\\DessertListUserRepository',
            'validator' => '?',
        ]);
    }
}
