<?php

namespace ContainerFxsV89x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N9lCwcdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n9lCwcd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n9lCwcd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dessertListUserRepository' => ['privates', 'App\\Repository\\DessertListUserRepository', 'getDessertListUserRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'dessertListUserRepository' => 'App\\Repository\\DessertListUserRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
