<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTGHPWgH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTGHPWgH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTGHPWgH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTGHPWgH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTGHPWgH\App_KernelDevDebugContainer([
    'container.build_hash' => 'TGHPWgH',
    'container.build_id' => 'e54e7d03',
    'container.build_time' => 1669029251,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTGHPWgH');
