<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDCnD1aU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDCnD1aU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDCnD1aU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDCnD1aU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDCnD1aU\App_KernelDevDebugContainer([
    'container.build_hash' => 'DCnD1aU',
    'container.build_id' => '9931955b',
    'container.build_time' => 1669044674,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDCnD1aU');
