<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'list_create' => [[], ['_controller' => 'App\\Controller\\DessertListUserController::create'], [], [['text', '/list']], [], []],
    'list_delete' => [['id'], ['_controller' => 'App\\Controller\\DessertListUserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/lists']], [], []],
    'list_get' => [[], ['_controller' => 'App\\Controller\\DessertListUserController::getDessertList'], [], [['text', '/lists']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'user_registration' => [[], ['_controller' => 'App\\Controller\\UsersController::registration'], [], [['text', '/register']], [], []],
    'information' => [[], ['_controller' => 'App\\Controller\\UsersController::information'], [], [['text', '/information']], [], []],
    'desserts_get' => [[], ['_controller' => 'App\\Controller\\LibraryController::list'], [], [['text', '/api/desserts']], [], []],
    'dessert_delete' => [['id'], ['_controller' => 'App\\Controller\\LibraryController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/desserts']], [], []],
    'create_dessert' => [[], ['_controller' => 'App\\Controller\\LibraryController::create'], [], [['text', '/api/dessert']], [], []],
    'dessertUser_create' => [[], ['_controller' => 'App\\Controller\\DessertsUserController::create'], [], [['text', '/list/dessertsUser']], [], []],
    'dessertUser_delete' => [['id'], ['_controller' => 'App\\Controller\\DessertsUserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/list/remove']], [], []],
    'dessertsUser_get' => [['idList'], ['_controller' => 'App\\Controller\\DessertsUserController::list'], [], [['variable', '/', '[^/]++', 'idList', true], ['text', '/list/dessertsUser']], [], []],
    'fos_js_routing_js' => [['_format'], ['_controller' => 'fos_js_routing.controller::indexAction', '_format' => 'js'], ['_format' => 'js|json'], [['variable', '.', 'js|json', '_format', true], ['text', '/js/routing']], [], []],
];
